# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-26 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskManager',
            new_name='Task',
        ),
    ]
